global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # Prometheus itself
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']

  # Container metrics
  - job_name: cadvisor
    static_configs:
      - targets: ['cadvisor:8080']

  # Host metrics
  - job_name: node
    static_configs:
      - targets: ['node-exporter:9100']

  # MySQL metrics
  - job_name: mysql
    static_configs:
      - targets: ['mysql-exporter:9104']

  # Nginx (web server) metrics
  - job_name: nginx
    static_configs:
      - targets: ['nginx-exporter:9113']
